FROM python:3.6
COPY requirements.txt .
COPY requirements-test.txt .
RUN pip install -r requirements.txt
RUN pip install -r requirements-test.txt
COPY ui /ui
COPY tests /tests
CMD coverage run -m unittest discover -s tests/ && coverage report --include ui/ui.py
